[project]
name = "circuijts"
version = "0.1.0"
description = "Circuit description language parser and validator"
authors = []
readme = "README.md"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["circuijt"]